### ISSUE TITLE
Update required for Readme file

### ISSUE THREAD

**Issue by amrs-tech** [amrs-tech/PDF-Mailer#1]

**Comment by rishabhp99** [comment]
I would like to contribute to the project.

**Comment by amrs-tech** [comment]
Okay carry on :) @rishabhp99

**Comment by zeddmaxx** [comment]
Hey, I'd like to work on this!

**Comment by amrs-tech** [comment]
@zeddmaxx Yeah. You can make PRs :)

**Comment by zeddmaxx** [comment]
Hey, so what exactly are you looking for in the Readme.md ?

**Comment by amrs-tech** [comment]
You can try to understand the program and you can add up the way it executes in the Readme file.

**Comment by zeddmaxx** [comment]
Ohh okay!
